name: EpitechCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check_the_repository_state:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch-names
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.branch-names.outputs.head_ref_branch }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run coding style checker
        run: |
          nix run github:Sigmapitech/cs \
            --extra-experimental-features 'nix-command flakes' \
            -- . --ignore-rules=C-G1

      - name: Build project
        run: |
          make

      - name: Check for banned functions
        run: |
          nix build
          nix run github:Dawoox/efc -- \
            ./mysh \
            ./afunc.txt
